name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.x'  # Use the appropriate .NET Core version

    - name: Build the ASP.NET Core app
      run: dotnet build ./VJAUDIO.csproj  # Replace with your project file

    - name: Publish the ASP.NET Core app
      run: dotnet publish ./VJAUDIO.csproj -c Release -o publish

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./VJAUDIO/publish  # Replace with your actual publish directory
